// Phase 7 — machine-readable docs/audit artifacts.
//
// Writes docs/audit/findings.json, coverage.json, engine-mismatches.json,
// each Ajv-validated against its schema before hitting disk so scanner drift
// fails loud. The seeded per-family markdown is regenerated by seeder.ts;
// these JSON files are the shared source of truth that downstream tooling
// (and eventually the seeder) can read back.

import { promises as fs } from 'node:fs';
import * as path from 'node:path';

import type { CoverageMatrix } from './coverage/matrix';
import {
  validateCoverageReport,
  validateEngineMismatchReport,
  validateFindingsReport,
  type CoverageReport,
  type EngineMismatchReport,
  type FindingsReport,
} from './ir-schema';
import { compareFindings, type Finding, type FindingConfidence, type FindingSeverity } from './types';

export interface DocsArtifactsInputs {
  findings: Finding[];
  scansRun: string[];
  startedAt: string;
  durationMs: number;
  coverage: CoverageMatrix;
}

export async function writeDocsArtifacts(
  docsAuditDir: string,
  inputs: DocsArtifactsInputs,
): Promise<void> {
  await fs.mkdir(docsAuditDir, { recursive: true });

  const materialized = [...inputs.findings]
    .map(materializeConfidence)
    .sort(compareFindings);

  const findingsReport = buildFindingsReport(materialized, inputs);
  validateFindingsReport(findingsReport);

  const coverageReport = buildCoverageReport(inputs.coverage, inputs.startedAt);
  validateCoverageReport(coverageReport);

  const engineMismatchReport = buildEngineMismatchReport(materialized, inputs.startedAt);
  validateEngineMismatchReport(engineMismatchReport);

  await Promise.all([
    fs.writeFile(
      path.join(docsAuditDir, 'findings.json'),
      JSON.stringify(findingsReport, null, 2) + '\n',
      'utf8',
    ),
    fs.writeFile(
      path.join(docsAuditDir, 'coverage.json'),
      JSON.stringify(coverageReport, null, 2) + '\n',
      'utf8',
    ),
    fs.writeFile(
      path.join(docsAuditDir, 'engine-mismatches.json'),
      JSON.stringify(engineMismatchReport, null, 2) + '\n',
      'utf8',
    ),
  ]);
}

// ============================================================
// Builders
// ============================================================

export function materializeConfidence(f: Finding): Finding {
  return f.confidence ? f : { ...f, confidence: 'DETERMINISTIC' };
}

export function buildFindingsReport(
  findings: Finding[],
  inputs: Pick<DocsArtifactsInputs, 'scansRun' | 'startedAt' | 'durationMs'>,
): FindingsReport {
  return {
    schemaVersion: 2,
    startedAt: inputs.startedAt,
    durationMs: inputs.durationMs,
    scansRun: inputs.scansRun,
    counts: countBySeverity(findings),
    countsByConfidence: countByConfidence(findings),
    findings,
  };
}

export function buildCoverageReport(
  coverage: CoverageMatrix,
  generatedAt: string,
): CoverageReport {
  return {
    schemaVersion: 1,
    generatedAt,
    overall: coverage.overall,
    byFamily: coverage.byFamily,
  };
}

export function buildEngineMismatchReport(
  findings: Finding[],
  generatedAt: string,
): EngineMismatchReport {
  const mismatches = findings.filter((f) => f.confidence === 'ENGINE_MISMATCH');
  const countsByScan: Record<string, number> = {};
  for (const f of mismatches) {
    countsByScan[f.scanId] = (countsByScan[f.scanId] ?? 0) + 1;
  }
  return {
    schemaVersion: 1,
    generatedAt,
    count: mismatches.length,
    countsByScan,
    findings: mismatches,
  };
}

// ============================================================
// Local count helpers
// ============================================================

function countBySeverity(findings: Finding[]): Record<FindingSeverity, number> {
  const out: Record<FindingSeverity, number> = {
    CRITICAL: 0,
    MAJOR: 0,
    MINOR: 0,
    POLISH: 0,
  };
  for (const f of findings) out[f.severity]++;
  return out;
}

function countByConfidence(findings: Finding[]): Record<FindingConfidence, number> {
  const out: Record<FindingConfidence, number> = {
    DETERMINISTIC: 0,
    RUNTIME_GROUNDED: 0,
    HEURISTIC: 0,
    ENGINE_MISMATCH: 0,
  };
  for (const f of findings) out[f.confidence ?? 'DETERMINISTIC']++;
  return out;
}
