import { useState, useContext, useCallback, useEffect } from 'react';

import { StatsBar } from './components/StatsBar';
import { PhaseIndicator } from './components/PhaseIndicator';
import { SeasonDawn } from './phases/SeasonDawn';
import { CrisisPhase } from './phases/CrisisPhase';
import { PetitionPhase } from './phases/PetitionPhase';
import { DecreePhase } from './phases/DecreePhase';
import { SummaryPhase } from './phases/SummaryPhase';
import { GameContext } from '../context/game-context';
import { resolveTurn } from '../engine/resolution/turn-resolution';
import { surfaceEvents } from '../engine/events/event-engine';
import { calculateCategoryWeights } from '../engine/events/narrative-pacing';
import { EVENT_POOL } from '../data/events/index';
import type { ActiveEvent, GameState } from '../engine/types';
import type { RoundPhase, PhaseDecisions } from './types';
import { partitionEvents } from '../bridge/eventClassifier';
import { generateCrisisPhaseData } from '../bridge/crisisCardGenerator';
import type { CrisisPhaseData } from '../bridge/crisisCardGenerator';
import { generatePetitionCards } from '../bridge/petitionCardGenerator';
import type { PetitionCardData } from '../bridge/petitionCardGenerator';
import { generateDecreeCards } from '../bridge/decreeCardGenerator';
import type { DecreeCardData } from '../bridge/decreeCardGenerator';
import { generateAdvisorBriefing } from '../bridge/advisorGenerator';
import type { AdvisorBriefing } from '../bridge/advisorGenerator';
import { generateSummaryData } from '../bridge/summaryGenerator';
import type { SummaryData } from '../bridge/summaryGenerator';
import { mapDecisionsToActions } from '../bridge/decisionMapper';

const PHASE_ORDER: RoundPhase[] = ['seasonDawn', 'crisis', 'petition', 'decree', 'summary'];

const INITIAL_DECISIONS: PhaseDecisions = {
  crisisResponse: null,
  petitionDecisions: [],
  selectedDecrees: [],
};

export function RoundController() {
  const ctx = useContext(GameContext);
  if (!ctx) throw new Error('RoundController must be inside GameProvider');

  const [currentPhase, setCurrentPhase] = useState<RoundPhase>('seasonDawn');
  const [decisions, setDecisions] = useState<PhaseDecisions>(INITIAL_DECISIONS);

  // Bridge data for this round
  const [surfacedEvents, setSurfacedEvents] = useState<ActiveEvent[]>([]);
  const [crisisData, setCrisisData] = useState<CrisisPhaseData | null>(null);
  const [petitionCards, setPetitionCards] = useState<PetitionCardData[]>([]);
  const [decreeCards, setDecreeCards] = useState<DecreeCardData[]>([]);
  const [advisorBriefing, setAdvisorBriefing] = useState<AdvisorBriefing | null>(null);
  const [summaryData, setSummaryData] = useState<SummaryData | null>(null);
  // Random selections for Season Dawn — computed in prepareRound (inside a useEffect)
  // so Math.random() is never called during the render phase.
  const [seasonPhraseIndex, setSeasonPhraseIndex] = useState(0);
  const [seasonEffectOrder, setSeasonEffectOrder] = useState<[number, number, number]>([0, 1, 2]);

  // Pre-generate card pools when the season dawn phase begins
  useEffect(() => {
    if (currentPhase === 'seasonDawn') {
      prepareRound(ctx.state.gameState, ctx.state.eventHistory);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentPhase]);

  function prepareRound(gameState: GameState, eventHistory: ActiveEvent[]) {
    // Use events already generated by Phase 9 of the previous turn's resolution.
    // Only call surfaceEvents on the very first turn when activeEvents is empty.
    let events: ActiveEvent[];
    if (gameState.activeEvents.length > 0) {
      events = gameState.activeEvents;
    } else {
      const categoryWeights = calculateCategoryWeights(
        gameState.narrativePacing,
        gameState.turn.turnNumber,
      );
      events = surfaceEvents(
        gameState,
        gameState.turn.turnNumber,
        EVENT_POOL,
        gameState.activeEvents,
        eventHistory,
        categoryWeights,
      );
    }
    setSurfacedEvents(events);

    const { crisisEvents, petitionEvents } = partitionEvents(events);

    const firstCrisis = crisisEvents[0] ?? null;
    const crisis = firstCrisis ? generateCrisisPhaseData(firstCrisis) : null;
    setCrisisData(crisis);
    setPetitionCards(generatePetitionCards(petitionEvents));
    setDecreeCards(generateDecreeCards(gameState));
    setAdvisorBriefing(generateAdvisorBriefing(gameState));
    setSummaryData(null);

    // Randomize Season Dawn display — safe here because prepareRound runs inside a useEffect
    setSeasonPhraseIndex(Math.floor(Math.random() * 3));
    const order = [0, 1, 2] as [number, number, number];
    for (let i = 2; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [order[i], order[j]] = [order[j], order[i]];
    }
    setSeasonEffectOrder(order);
  }

  const advancePhase = useCallback(
    (phaseDecisions?: Partial<PhaseDecisions>) => {
      setDecisions((prev: PhaseDecisions) => {
        const updated = phaseDecisions ? { ...prev, ...phaseDecisions } : prev;

        const currentIndex = PHASE_ORDER.indexOf(currentPhase);
        if (currentIndex < PHASE_ORDER.length - 1) {
          const nextPhase = PHASE_ORDER[currentIndex + 1];

          // Generate summary data when transitioning to summary phase
          if (nextPhase === 'summary') {
            const finalDecisions = updated;
            const prevStyle = ctx.state.gameState.rulingStyle;
            setSummaryData(
              generateSummaryData(finalDecisions, crisisData, petitionCards, prevStyle, prevStyle),
            );
          }

          setCurrentPhase(nextPhase);
        }

        return updated;
      });
    },
    [currentPhase, crisisData, petitionCards, ctx.state.gameState.rulingStyle],
  );

  const handleRoundComplete = useCallback(() => {
    try {
      const cardActions = mapDecisionsToActions(decisions, crisisData, petitionCards, decreeCards);
      // Merge card-derived actions with any actions already queued via QUEUE_ACTION dispatch
      // (e.g. military deployments, construction, espionage operations).
      const existingActions = ctx.state.gameState.actionBudget.queuedActions;
      const allActions = [...existingActions, ...cardActions];
      const totalSlots = allActions.reduce((sum, a) => sum + a.slotCost, 0);

      const stateWithActions: GameState = {
        ...ctx.state.gameState,
        activeEvents: [
          ...ctx.state.gameState.activeEvents,
          ...surfacedEvents,
        ],
        actionBudget: {
          ...ctx.state.gameState.actionBudget,
          queuedActions: allActions,
          slotsUsed: totalSlots,
          slotsRemaining: Math.max(
            0,
            ctx.state.gameState.actionBudget.slotsTotal - totalSlots,
          ),
        },
      };

      const result = resolveTurn(stateWithActions, (s) => s, ctx.state.eventHistory);
      ctx.dispatch({ type: 'TURN_RESOLVED', result });
    } catch (err) {
      console.error('Turn resolution error:', err);
    }

    setCurrentPhase('seasonDawn');
    setDecisions(INITIAL_DECISIONS);
    setSurfacedEvents([]);
  }, [ctx, decisions, crisisData, petitionCards, decreeCards, surfacedEvents]);

  return (
    <div
      style={{
        width: '100%',
        maxWidth: 430,
        padding: '0 16px 30px',
        display: 'flex',
        flexDirection: 'column',
        gap: 12,
      }}
    >
      <StatsBar />
      <PhaseIndicator activePhase={currentPhase} />

      {currentPhase === 'seasonDawn' && (
        <SeasonDawn
          advisorBriefing={advisorBriefing ?? undefined}
          phraseIndex={seasonPhraseIndex}
          effectOrder={seasonEffectOrder}
          onComplete={() => advancePhase()}
        />
      )}
      {currentPhase === 'crisis' && (
        <CrisisPhase
          crisisData={crisisData ?? undefined}
          onComplete={(response) => advancePhase({ crisisResponse: response })}
        />
      )}
      {currentPhase === 'petition' && (
        <PetitionPhase
          petitionCards={petitionCards}
          onComplete={(petitionDecisions) => advancePhase({ petitionDecisions })}
        />
      )}
      {currentPhase === 'decree' && (
        <DecreePhase
          decreeCards={decreeCards}
          onComplete={(selectedDecrees) => advancePhase({ selectedDecrees })}
        />
      )}
      {currentPhase === 'summary' && (
        <SummaryPhase
          decisions={decisions}
          summaryData={summaryData ?? undefined}
          onComplete={handleRoundComplete}
        />
      )}
    </div>
  );
}
