// gameplay-blueprint.md §5.1 — Action Budget System
// Pure engine logic for 3-slot budget rules, action validation, and cost deduction.
// No React imports. No player-facing text.

import { ActionBudget, ActionType, QueuedAction } from '../types';
import { ACTION_BUDGET_BASE, POLICY_CHANGES_PER_TURN } from '../constants';

// ============================================================
// Public Types
// ============================================================

/**
 * Describes why a queued action was rejected.
 * The code identifies the violation; player-facing text is generated by the data layer.
 */
export interface ActionValidationError {
  code: 'BUDGET_EXHAUSTED' | 'INSUFFICIENT_SLOTS' | 'POLICY_LIMIT_REACHED';
}

// ============================================================
// Exported Functions
// ============================================================

/**
 * Validates whether an action can be added to the current budget.
 *
 * Rules (§5.1):
 * - PolicyChange: uses its own counter (policyChangesUsedThisTurn), not action slots.
 *   Limit is POLICY_CHANGES_PER_TURN (1 per turn).
 * - Free actions (isFree === true): always valid; no slot consumption.
 * - CrisisResponse with isFree === false: treated as a standard 1-slot action.
 * - All other actions: must have sufficient slotsRemaining for action.slotCost.
 *
 * Returns null if valid; an ActionValidationError if rejected.
 */
export function validateActionAddition(
  action: QueuedAction,
  budget: ActionBudget,
): ActionValidationError | null {
  if (action.type === ActionType.PolicyChange) {
    if (budget.policyChangesUsedThisTurn >= POLICY_CHANGES_PER_TURN) {
      return { code: 'POLICY_LIMIT_REACHED' };
    }
    return null;
  }

  if (action.isFree) {
    return null;
  }

  if (budget.slotsRemaining <= 0) {
    return { code: 'BUDGET_EXHAUSTED' };
  }

  if (action.slotCost > budget.slotsRemaining) {
    return { code: 'INSUFFICIENT_SLOTS' };
  }

  return null;
}

/**
 * Deducts the action's cost from the budget and appends it to the queue.
 * Returns a new ActionBudget (immutable update).
 *
 * Callers must call validateActionAddition first; this function does not
 * re-validate. Deducting an over-budget action results in negative slotsRemaining.
 */
export function deductActionCost(budget: ActionBudget, action: QueuedAction): ActionBudget {
  if (action.type === ActionType.PolicyChange) {
    return {
      ...budget,
      policyChangesUsedThisTurn: budget.policyChangesUsedThisTurn + 1,
      queuedActions: [...budget.queuedActions, action],
    };
  }

  if (action.isFree) {
    return {
      ...budget,
      queuedActions: [...budget.queuedActions, action],
    };
  }

  const newSlotsUsed = budget.slotsUsed + action.slotCost;
  return {
    ...budget,
    slotsUsed: newSlotsUsed,
    slotsRemaining: budget.slotsTotal - newSlotsUsed,
    queuedActions: [...budget.queuedActions, action],
  };
}

/**
 * Returns true when no action slots remain.
 * Free actions and PolicyChanges can still be added when this returns true.
 */
export function checkActionBudgetExhausted(budget: ActionBudget): boolean {
  return budget.slotsRemaining <= 0;
}

/**
 * Resets the action budget for the start of a new turn.
 * Clears the action queue and zeroes all counters.
 * Returns a fresh ActionBudget (immutable; does not mutate the input).
 */
export function resetActionBudgetForNextTurn(): ActionBudget {
  return {
    slotsTotal: ACTION_BUDGET_BASE,
    slotsUsed: 0,
    slotsRemaining: ACTION_BUDGET_BASE,
    policyChangesUsedThisTurn: 0,
    queuedActions: [],
  };
}
